return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "astro",
      "bash",
      "dockerfile",
      "javascript",
      "json",
      "jsonc",
      "lua",
      "luap",
      "markdown",
      "php",
      "sql",
      "twig",
      "typescript",
      "yaml",
    },
    highlight = { enable = true, additional_vim_regex_highlighting = { "php" } },
    indent = { enable = false },
    autotag = {
      enable = true,
      filetypes = {
        "html",
        "javascript",
        "javascriptreact",
        "svelte",
        "typescript",
        "typescriptreact",
        "vue",
        "xml",
        "php",
      },
    },
  },
}
